// 环境监测新数据国际化文件 (English)
// Environment New Data i18n File
export default {
  title: 'Environment New Data',
  subtitle: 'Manage environmental monitoring data records',
  list: 'Data List',
  add: 'Add Record',
  edit: 'Edit Record',
  detail: 'Record Details',
  delete: 'Delete Record',
  deleteConfirm: 'Are you sure you want to delete this record?',
  deleteSuccess: 'Deleted successfully',
  addSuccess: 'Added successfully',
  editSuccess: 'Updated successfully',

  // Search & Filter
  searchPlaceholder: 'Search station ID',
  filterByParameter: 'Filter by parameter',
  filterByBatch: 'Filter by batch',
  allParameters: 'All Parameters',
  allBatches: 'All Batches',

  // Parameter Codes
  parameterCode: {
    RAIN_DAILY: 'Daily Rainfall',
    TMAX: 'Max Temperature',
    TMIN: 'Min Temperature',
    HUMIDITY: 'Humidity',
    WIND_SPEED: 'Wind Speed',
    SOLAR_RAD: 'Solar Radiation',
    other: 'Other',
  },

  // Form Fields
  form: {
    plotInfo: 'Plot Information',
    stationInfo: 'Station Information',
    basicInfo: 'Basic Information',
    measurementInfo: 'Unit',
    envRecordId: 'Record ID',
    trialId: 'Trial ID',
    batchId: 'Batch ID',
    plotId: 'Plot ID',
    stationId: 'Station ID',
    timestamp: 'Timestamp',
    parameterCode: 'Parameter Code',
    value: 'Value',
    unit: 'Unit',
    source: 'Data Source',
    remark: 'Remarks',
    observerId: 'Observer ID',
  },

  // Form Placeholders
  placeholder: {
    envRecordId: 'Auto-generated by system',
    trialId: 'Please select trial',
    batchId: 'Please select batch',
    plotId: 'Please select plot (optional)',
    stationId: 'Please enter station ID',
    timestamp: 'Please select timestamp',
    parameterCode: 'Please select parameter code',
    value: 'Please enter value',
    unit: 'Please enter unit (e.g., mm, °C)',
    source: 'Please enter data source',
    remark: 'Please enter remarks (optional)',
  },

  // Form Validation Rules
  rules: {
    batchIdRequired: 'Please select batch',
    trialIdRequired: 'Please select trial',
    stationIdRequired: 'Station ID is required',
    stationIdLength: 'Station ID cannot exceed 50 characters',
    timestampRequired: 'Please select timestamp',
    parameterCodeRequired: 'Please select parameter code',
    valueRequired: 'Please enter value',
    valueFormat: 'Please enter valid number',
    unitRequired: 'Please enter unit',
    unitLength: 'Unit cannot exceed 20 characters',
    sourceLength: 'Source cannot exceed 100 characters',
    remarkLength: 'Remarks cannot exceed 500 characters',
  },

  // Table Columns
  columns: {
    envRecordId: 'Record ID',
    trialId: 'Trial ID',
    batchId: 'Batch ID',
    batchName: 'Batch Name',
    plotId: 'Plot ID',
    plotName: 'Plot Name',
    stationId: 'Station ID',
    timestamp: 'Timestamp',
    parameterCode: 'Parameter',
    value: 'Value',
    unit: 'Unit',
    source: 'Source',
    createBy: 'Created By',
    createTime: 'Created Time',
    updateTime: 'Updated Time',
    updateBy: 'Updated By',
    auditBy: 'Audited By',
    auditTime: 'Audit Time',
    auditStatus: 'Audit Status',
    actions: 'Actions',
  },
}
