export default {
  // Input Categories
  category: {
    seed: 'Seed',
    fertilizer: 'Fertilizer',
    pesticide: 'Pesticide',
    other: 'Other'
  },

  menu: {
    inputQuota: 'Input Quota Allocation Management',
  },

  // State Annual Quota Management
  stateQuota: {
    title: 'State Annual Quota Management',
    subtitle: 'Manage annual agricultural input quotas for Oromia State',
    list: 'Quota List',
    add: 'Add Quota',
    edit: 'Edit Quota',
    detail: 'Quota Details',
    delete: 'Delete Quota',
    deleteConfirm: 'Are you sure you want to delete this quota? This action cannot be undone.',
    batchDeleteConfirm: 'Are you sure you want to delete the selected quotas? This action cannot be undone.',
    deleteSuccess: 'Deleted successfully',
    addSuccess: 'Added successfully',
    editSuccess: 'Updated successfully',

    // Table Columns
    columns: {
      quotaName: 'Quota Name',
      year: 'Year',
      category: 'Input Category',
      totalQuota: 'Total Quota',
      operator: 'Operator',
      operatorDivision: 'Division',
      operateTime: 'Operation Time',
      createTime: 'Create Time',
      updateTime: 'Update Time',
      modifier: 'Modifier',
      actions: 'Actions'
    },

    // Form
    form: {
      basicInfo: 'Basic Information',
      operatorInfo: 'Operator Information',
      year: 'Quota Year',
      category: 'Input Category',
      totalQuota: 'Total Annual Quota',
      quotaName: 'Quota Name'
    },

    // Placeholders
    placeholder: {
      year: 'Please select quota year',
      category: 'Please select input category',
      totalQuota: 'Please enter total annual quota',
      quotaName: 'Auto-generated by system'
    }
  },

  // Quota Allocation Management
  allocation: {
    title: 'Quota Allocation Management',
    subtitle: 'Allocate quotas hierarchically from State-Zone-Worede-Kebele-Farmer',
    list: 'Allocation Records',
    add: 'Add Allocation',
    edit: 'Edit Allocation',
    detail: 'Allocation Details',
    delete: 'Delete Allocation',
    deleteConfirm: 'Are you sure you want to delete this allocation record? This action cannot be undone.',
    batchDeleteConfirm: 'Are you sure you want to delete the selected allocation records? This action cannot be undone.',
    deleteSuccess: 'Deleted successfully',
    addSuccess: 'Added successfully',
    editSuccess: 'Updated successfully',

    // Table Columns
    columns: {
      allocationName: 'Allocation Name',
      year: 'Year',
      category: 'Input Category',
      fromDivision: 'From Division',
      fromLevel: 'From Level',
      toDivision: 'To Division',
      parentDivision: 'Parent Division',
      quotaName: 'Related State Quota',
      totalReceived: 'Total Received',
      allocatedQuota: 'Allocated Quota',
      totalAllocated: 'Total Allocated',
      remainingQuota: 'Remaining Quota',
      status: 'Status',
      operator: 'Operator',
      operatorDivision: 'Operator Division',
      operateTime: 'Operation Time',
      progressUpdateTime: 'Progress Update Time',
      createTime: 'Create Time',
      updateTime: 'Update Time',
      modifier: 'Modifier',
      modifierDivision: 'Modifier Division',
      actions: 'Actions'
    },

    // Division Levels
    level: {
      region: 'Region',
      zone: 'Zone',
      worede: 'Worede',
      kebele: 'Kebele'
    },

    // Allocation Status
    status: {
      notAllocated: 'Not Allocated',
      partiallyAllocated: 'Partially Allocated',
      completed: 'Completed'
    },

    // Form
    form: {
      basicInfo: 'Basic Information',
      quotaDetails: 'Quota Details',
      operatorInfo: 'Operator Information',
      year: 'Allocation Year',
      category: 'Input Category',
      fromDivisionLevel: 'From Division Level',
      fromDivisionId: 'From Division ID',
      toDivisionId: 'To Division ID',
      toFarmerId: 'To Farmer ID',
      allocatedQuota: 'Allocated Quota',
      totalReceivedQuota: 'Total Received Quota',
      quotaId: 'Related State Quota ID'
    },

    // Placeholders
    placeholder: {
      year: 'Please select allocation year',
      category: 'Please select input category',
      level: 'Please select division level',
      fromDivisionId: 'Please enter from division ID',
      toDivisionId: 'Please enter to division ID',
      toFarmerId: 'Please enter to farmer ID',
      allocatedQuota: 'Please enter allocated quota',
      totalReceivedQuota: 'Please enter total received quota',
      quotaId: 'Please enter related state quota ID',
      status: 'Please select allocation status'
    }
  }
}
